spring:
  application:
    name: auth-service
  config:
#    import: optional:configserver:http://config-server-con:8888
    import: optional:configserver:http://localhost:8888
#    import: optional:configserver:http://config-server-con:8888
#  data:
#    redis:
#      host: ${SPRING_REDIS_HOST:localhost}
#      port: ${SPRING_REDIS_PORT:6379}
#      database: 3
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/my_restaurant_auth-service
#    username: root
#    password: omid@1999
#  cloud:
#    config:
#      enabled: false
#    discovery:
#      enabled: false
server:
  port: 9090

#app:
#  security:
#    issuer: ${spring.application.name}
#    expire: 36000
#    secret-key: my-name-is-omid
app:
  security:
    issuer: ${spring.application.name}
    expire: 60000
    keys-dir: file:///D:/projects/keys/my-restaurant

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-server-con:8761/eureka
