spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8082

