server:
  port: 8280
spring:
  data:
    redis:
      host: 192.168.1.13
      port: 6379
      database: 4
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/api/auth/oauth2/jwks