spring:
  application:
    name: order-service
  #  data:
  #    mongodb:
  #      database: my_restaurant
  #      authentication-database: admin
  #      host: localhost
  #      port: 27017
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8082
