spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/projects/external-configs/my-restaurant
#          uri: /home/omid/tamrins/external-config/my-restaurant
server:
  port: 8888
