server:
  port: 8080
spring:
  application:
    name: food-service
  config:
    import: optional:configserver:http://localhost:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/api/auth/oauth2/jwks
